### ISSUE TITLE
Support for Redmine 4.x

### ISSUE THREAD

**Issue by mboremski** [braini75/msproject_import#23]
Please consider updateing compatibility to redmine 4.x
Trieng to Install this Plugin on redmine 4.0.4 leads to:

```
***/redmine/plugins# RAILS_ENV=production rake redmine:plugins:migrate
(in /opt/redmine)
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/opt/redmine/plugins/msproject_import/init.rb:1:in `<top (required)>'
[...]
```

### 1st thing to fix:
In `init.rb` replace
`ActionDispatch::Callbacks.to_prepare`
with:
`ActiveSupport::Reloader.to_prepare`

With this fix the plugin can be integrated

### 2nd thing to fix:
but redmine is not working due to:
(Apache2 log -> Web application could not be started)
```
undefined method `before_filter' for MsprojImpController:Class
Did you mean?  before_action (NoMethodError)
  /opt/redmine/plugins/msproject_import/app/controllers/msproj_imp_controller.rb:8:in `<class:MsprojImpController>'
```
this can be replaced by using `before_filter` in stated file.
(found here: https://stackoverflow.com/questions/45015651/undefined-method-for-before-filter) 

### 3rd thing to fix:
Now it shows:
```
  Message from application: undefined method `after_filter' for MsprojImpController:Class
Did you mean?  after_action (NoMethodError)
  /opt/redmine/plugins/msproject_import/app/controllers/msproj_imp_controller.rb:9:in `<class:MsprojImpController>'
```

That can be solved by replacing `after_filter` by `after_action`

After that he lugin is useable in redmine 4.0.4
Would be happy if someone can confirm.

Maybe Ill do a fork and create a PR with these changes after some tests.
Hopefully this project is not dead...

**Comment by mboremski** [comment]
Managed to get it working.
Suggestions are welcome.
